# -*- coding: utf-8 -*-
"""Tugas3_PKT_NasywaBefiputr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McL_dUOmEiyCnxebC0c_0zcvemIShQit

#TUGAS 2 - Membangun Convolutional Netwirk (CNN) di 'Keras' Menggunakan Dataset MNIST
MK Pengantar Kecerdasan Tiruan

Nasywa Befiputri - 2203015044

##Import seluruh Library
"""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten

"""##Loading dataset"""

(x_train, y_train), (x_test, y_test) = mnist.load_data()

"""##Data Pre-Processing"""

x_train = x_train.reshape(60000, 28, 28, 1).astype('float32') / 255.0  # Normalize pixel values to [0, 1]
x_test = x_test.reshape(10000, 28, 28, 1).astype('float32') / 255.0

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

"""##CNN Arsitektur"""

model = Sequential()

model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

"""##Compiling Model"""

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

"""##Training Model"""

model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))
